import 'dart:js';

import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
final List<String> date = [
  "1950",
  "1951",
  "1952",
  "1953",
  "1954",
  "1955",
  "1956",
  "1957",
  "1958",
  "1959",
  "1960",
  "1961",
  "1962",
  "1963",
  "1964",
  "1965",
  "1966",
  "1967",
  "1968",
  "1969",
  "1970",
  "1971",
  "1972",
  "1973",
  "1974",
  "1975",
  "1976",
  "1977",
  "1978",
  "1979",
  "1980",
  "1981",
  "1982",
  "1983",
  "1984",
  "1985",
  "1986",
  "1987",
  "1988",
  "1989",
  "1990",
  "1991",
  "1992",
  "1993",
  "1994",
  "1995",
  "1996",
  "1997",
  "1998",
  "1999",
  "2000",
  "2001",
  "2002",
  "2003",
  "2004",
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024"
];
final List<String> cities = [
AppLocalizations.of(context as BuildContext)!.alexandria,
  AppLocalizations.of(context as BuildContext)!.cairo,
  AppLocalizations.of(context as BuildContext)!.giza,
  AppLocalizations.of(context as BuildContext)!.shubraElKheima,
  AppLocalizations.of(context as BuildContext)!.portSaid,
  AppLocalizations.of(context as BuildContext)!.suez,
  AppLocalizations.of(context as BuildContext)!.luxor,
  AppLocalizations.of(context as BuildContext)!.mansoura,
  AppLocalizations.of(context as BuildContext)!.elMahallaElKubra,
  AppLocalizations.of(context as BuildContext)!.tanta,
  AppLocalizations.of(context as BuildContext)!.asyut,
  AppLocalizations.of(context as BuildContext)!.ismailia,
  AppLocalizations.of(context as BuildContext)!.fayoum,
  AppLocalizations.of(context as BuildContext)!.zagazig,
  AppLocalizations.of(context as BuildContext)!.aswan,
  AppLocalizations.of(context as BuildContext)!.damietta,
  AppLocalizations.of(context as BuildContext)!.damanhur,
  AppLocalizations.of(context as BuildContext)!.minya,
  AppLocalizations.of(context as BuildContext)!.beniSuef,
  AppLocalizations.of(context as BuildContext)!.qena,
];
final List<String> countries = [
  AppLocalizations.of(context as BuildContext)!.saudiArabia,
  AppLocalizations.of(context as BuildContext)!.egypt,
  AppLocalizations.of(context as BuildContext)!.algeria,
  AppLocalizations.of(context as BuildContext)!.iraq,
  AppLocalizations.of(context as BuildContext)!.morocco,
  AppLocalizations.of(context as BuildContext)!.sudan,
  AppLocalizations.of(context as BuildContext)!.yemen,
  AppLocalizations.of(context as BuildContext)!.syria,
  AppLocalizations.of(context as BuildContext)!.tunisia,
  AppLocalizations.of(context as BuildContext)!.libya,
  AppLocalizations.of(context as BuildContext)!.jordan,
  AppLocalizations.of(context as BuildContext)!.unitedArabEmirates,
  AppLocalizations.of(context as BuildContext)!.lebanon,
  AppLocalizations.of(context as BuildContext)!.kuwait,
  AppLocalizations.of(context as BuildContext)!.oman,
  AppLocalizations.of(context as BuildContext)!.qatar,
  AppLocalizations.of(context as BuildContext)!.bahrain,
  AppLocalizations.of(context as BuildContext)!.somalia,
  AppLocalizations.of(context as BuildContext)!.mauritania,
  AppLocalizations.of(context as BuildContext)!.djibouti,
];
final List<String> units = [
  AppLocalizations.of(context as BuildContext)!.meter,
  AppLocalizations.of(context as BuildContext)!.kilogram,
  AppLocalizations.of(context as BuildContext)!.second,
  AppLocalizations.of(context as BuildContext)!.liter,
  AppLocalizations.of(context as BuildContext)!.degreecelsius,
  AppLocalizations.of(context as BuildContext)!.gram,
  AppLocalizations.of(context as BuildContext)!.hour,
  AppLocalizations.of(context as BuildContext)!.millimeter,
  AppLocalizations.of(context as BuildContext)!.watt,
  AppLocalizations.of(context as BuildContext)!.volt,
  AppLocalizations.of(context as BuildContext)!.ampere,
  AppLocalizations.of(context as BuildContext)!.hertz,
  AppLocalizations.of(context as BuildContext)!.byte,
  AppLocalizations.of(context as BuildContext)!.megabyte,
  AppLocalizations.of(context as BuildContext)!.gram,
  AppLocalizations.of(context as BuildContext)!.pascal,
  AppLocalizations.of(context as BuildContext)!.joule,
  AppLocalizations.of(context as BuildContext)!.kilopascal,
  AppLocalizations.of(context as BuildContext)!.kilojoule,
  AppLocalizations.of(context as BuildContext)!.lumen,
];
