// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNNfENSYLuJtTqs8MJG8wcW5xwY6II5-A',
    appId: '1:979129892080:web:ee23f12d05e63a39811635',
    messagingSenderId: '979129892080',
    projectId: 'etradliing',
    authDomain: 'etradliing.firebaseapp.com',
    storageBucket: 'etradliing.appspot.com',
    measurementId: 'G-S5DPJDJJ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM-ivEyx4Cj5ZcSE29dobHp6tJYX2QraY',
    appId: '1:979129892080:android:1b399baa7983870e811635',
    messagingSenderId: '979129892080',
    projectId: 'etradliing',
    storageBucket: 'etradliing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVYNSMQA1nDlBqZBf8fyNEOscoZIm5QU',
    appId: '1:979129892080:ios:63cd936ac84c0939811635',
    messagingSenderId: '979129892080',
    projectId: 'etradliing',
    storageBucket: 'etradliing.appspot.com',
    iosBundleId: 'com.example.etradeling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVYNSMQA1nDlBqZBf8fyNEOscoZIm5QU',
    appId: '1:979129892080:ios:9e8e562dae28c115811635',
    messagingSenderId: '979129892080',
    projectId: 'etradliing',
    storageBucket: 'etradliing.appspot.com',
    iosBundleId: 'com.example.etradeling.RunnerTests',
  );
}
