// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYRHwVprAu0VBnW8YWGKxcclvBNtY9Us',
    appId: '1:118193198129:web:043d6313ff76481d3c7110',
    messagingSenderId: '118193198129',
    projectId: 'etradeling-d39a0',
    authDomain: 'etradeling-d39a0.firebaseapp.com',
    storageBucket: 'etradeling-d39a0.appspot.com',
    measurementId: 'G-RNF82MN68J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbCI0LkPkvAkll0AeRh8_G8B7ACu_Ntg',
    appId: '1:118193198129:android:05d1fecb5c4df7dc3c7110',
    messagingSenderId: '118193198129',
    projectId: 'etradeling-d39a0',
    storageBucket: 'etradeling-d39a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsT5ydivflZZXNUWMcfxLzod7QUpkGVyI',
    appId: '1:118193198129:ios:d1b988af14efd7a03c7110',
    messagingSenderId: '118193198129',
    projectId: 'etradeling-d39a0',
    storageBucket: 'etradeling-d39a0.appspot.com',
    iosBundleId: 'com.example.etradeling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsT5ydivflZZXNUWMcfxLzod7QUpkGVyI',
    appId: '1:118193198129:ios:d2acb940671ac8e13c7110',
    messagingSenderId: '118193198129',
    projectId: 'etradeling-d39a0',
    storageBucket: 'etradeling-d39a0.appspot.com',
    iosBundleId: 'com.example.etradeling.RunnerTests',
  );
}
