// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFXu-Y4op_oL4Xik-kdl1FealyN7FCxog',
    appId: '1:870687087470:web:9ae52f8f438f9318ea7f7f',
    messagingSenderId: '870687087470',
    projectId: 'etradeling-18174',
    authDomain: 'etradeling-18174.firebaseapp.com',
    storageBucket: 'etradeling-18174.appspot.com',
    measurementId: 'G-D02S32NS8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsOIp1QUmTDtF5aVt8sniQSDwSmvCu7M',
    appId: '1:870687087470:android:12232176cd9cf8bdea7f7f',
    messagingSenderId: '870687087470',
    projectId: 'etradeling-18174',
    storageBucket: 'etradeling-18174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpct8b_j_Cp4o9XZLcJ30wP8xrrud1a0',
    appId: '1:870687087470:ios:978eb2470b0dd56dea7f7f',
    messagingSenderId: '870687087470',
    projectId: 'etradeling-18174',
    storageBucket: 'etradeling-18174.appspot.com',
    iosBundleId: 'com.example.etradeling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwpct8b_j_Cp4o9XZLcJ30wP8xrrud1a0',
    appId: '1:870687087470:ios:6ff584c8551c85c0ea7f7f',
    messagingSenderId: '870687087470',
    projectId: 'etradeling-18174',
    storageBucket: 'etradeling-18174.appspot.com',
    iosBundleId: 'com.example.etradeling.RunnerTests',
  );
}
